name: cla-check
on: [pull_request]

jobs:
  cla-check:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v2
